# Learn Posture

use machine learning to recognize robot's posture (following the example in [scikit-learn-intro.ipynb](./scikit-learn-intro.ipynb) )

## 1. Data collection

We have colleceted data before, you need to add new data if you want to add new posture.

* the dateset are in *robot_pose_data* folder
* each file contains the data belongs to this posture, e.g. the data in *Back* file are collected when robot was in "Back" posture
* the data file can be load by ```pickle```, e.g. ```pickle.load(open('Back', 'rb'))```, the data is a list of feature data
* the features (e.g. each row of the data) are ['LHipYawPitch', 'LHipRoll', 'LHipPitch', 'LKneePitch', 'RHipYawPitch', 'RHipRoll', 'RHipPitch', 'RKneePitch', 'AngleX', 'AngleY'], where 'AngleX' and 'AngleY' are body angle (e.g. ```Perception.imu```) and others are joint angles.

## 2. Data preprocessing

In [61]:
%pylab inline

import pickle
from os import listdir, path
import numpy as np

from sklearn import svm, metrics

ROBOT_POSE_DATA_DIR = 'robot_pose_data'

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


c:\Users\willy\AppData\Local\Programs\Python\Python312\Lib\site-packages\IPython\core\magics\pylab.py:166: UserWarning: pylab import has clobbered these variables: ['clf']
`%matplotlib` prevents importing * from pylab and numpy
  warn("pylab import has clobbered these variables: %s"  % clobbered +


In [62]:
classes = listdir(ROBOT_POSE_DATA_DIR)
print(classes)


['Back', 'Belly', 'Crouch', 'Frog', 'HeadBack', 'Knee', 'Left', 'Right', 'Sit', 'Stand', 'StandInit']


In [102]:
def load_pose_data(i):
    '''load pose data from file'''
    data = []
    target = []
    # YOUR CODE HERE

    
    filename = path.join(ROBOT_POSE_DATA_DIR, classes[i])
    
    #data1 = pickle.load(open(filename, 'rb')) #(this caused this Error message: "ValueError: could not convert string to float")

    with open(filename, 'rb') as file: #This approch didn't
        lines = file.readlines()

        for line in lines:
            counter = -1
            tempArray = []
            if b"lp" in line:
                data.append(tempArray)
                counter +=1
            
            if b"F" in line:
                 zahl = float(line.split(b'F')[1].strip())
                 data[counter].append(zahl)
            elif b"I" in line:
                zahl = float(line.split(b'I')[1].strip())
                data[counter].append(zahl)
            
            """elif b"g" in line:
                zahl = float(line.split(b'g')[1].strip())
                data[counter].append(zahl)"""
            
            
        #clean data
        while [] in data:
            data.remove([])
    
    target = [i] * len(data)

    dataArray = np.array(data)
    targetArray = np.array(target)
    print(dataArray)
    return data, target
load_pose_data(0)

[[-0.05058002 -0.22698998 -0.8298521   1.71803808 -0.05058002 -0.14875603
  -0.93118     1.8945322  -0.0089925  -1.51652062]
 [-0.05058002 -0.22698998 -0.8298521   1.71803808 -0.05058002 -0.14875603
  -0.93118     1.89606619 -0.00688345 -1.52035582]
 [-0.05058002 -0.22698998 -0.8298521   1.7165041  -0.05058002 -0.14875603
  -0.93118     1.8945322  -0.00688345 -1.52016413]
 [-0.05058002 -0.22698998 -0.8298521   1.7165041  -0.05058002 -0.14875603
  -0.93118     1.8945322  -0.00707514 -1.51997244]
 [-0.05058002 -0.22698998 -0.8298521   1.7165041  -0.05058002 -0.14875603
  -0.92964602  1.8945322  -0.00726682 -1.51997244]
 [-0.05058002 -0.22698998 -0.8298521   1.71803808 -0.05058002 -0.14875603
  -0.93118     1.8945322  -0.00726682 -1.51978028]
 [-0.05058002 -0.22698998 -0.8298521   1.7165041  -0.05058002 -0.14875603
  -0.93118     1.8945322  -0.00688345 -1.52169764]
 [-0.05058002 -0.22852397 -0.8298521   1.7165041  -0.05058002 -0.14875603
  -0.93118     1.89606619 -0.0089925  -1.51345265]


([[-0.05058002471923828,
   -0.2269899845123291,
   -0.8298521041870117,
   1.7180380821228027,
   -0.05058002471923828,
   -0.1487560272216797,
   -0.9311800003051758,
   1.8945322036743164,
   -0.008992496877908707,
   -1.516520619392395],
  [-0.05058002471923828,
   -0.2269899845123291,
   -0.8298521041870117,
   1.7180380821228027,
   -0.05058002471923828,
   -0.1487560272216797,
   -0.9311800003051758,
   1.8960661888122559,
   -0.006883446592837572,
   -1.5203558206558228],
  [-0.05058002471923828,
   -0.2269899845123291,
   -0.8298521041870117,
   1.7165040969848633,
   -0.05058002471923828,
   -0.1487560272216797,
   -0.9311800003051758,
   1.8945322036743164,
   -0.006883446592837572,
   -1.520164132118225],
  [-0.05058002471923828,
   -0.2269899845123291,
   -0.8298521041870117,
   1.7165040969848633,
   -0.05058002471923828,
   -0.1487560272216797,
   -0.9311800003051758,
   1.8945322036743164,
   -0.007075135130435228,
   -1.5199724435806274],
  [-0.05058002471923828,
   -0

In [110]:
# load all the data
all_data = []
all_target = []
# YOUR CODE HERE
#I didnt know what you meant with All_Data so I implemented two approches.
#The first would just append every sublist of every pose to the all_data Array which would result in an total number of 204
#Thinking this could be the undesired result I implemented a second approch which would append EVERY Data into one huge array of all_data
#This would result in an total number of 2654

#First Approch

for pose in range(len(classes)): 

    poseList = load_pose_data(pose)[0]
    for lists in poseList:
        all_data.append(lists)
    poseTargets = load_pose_data(pose)[1]
    for targets in poseTargets:
        all_target.append(targets)

#Second Approch:
'''for i in range(len(classes)):
    for pose in load_pose_data(i)[0]:
        for element in pose:
            all_data.append(element)
    all_target.append(load_pose_data(i)[1])
'''
print("All Data:",all_data)
print("All targets: ", all_target)
print("total number of Targets: ", len(all_target))
print('total number of data', len(all_data))

[[-0.05058002 -0.22698998 -0.8298521   1.71803808 -0.05058002 -0.14875603
  -0.93118     1.8945322  -0.0089925  -1.51652062]
 [-0.05058002 -0.22698998 -0.8298521   1.71803808 -0.05058002 -0.14875603
  -0.93118     1.89606619 -0.00688345 -1.52035582]
 [-0.05058002 -0.22698998 -0.8298521   1.7165041  -0.05058002 -0.14875603
  -0.93118     1.8945322  -0.00688345 -1.52016413]
 [-0.05058002 -0.22698998 -0.8298521   1.7165041  -0.05058002 -0.14875603
  -0.93118     1.8945322  -0.00707514 -1.51997244]
 [-0.05058002 -0.22698998 -0.8298521   1.7165041  -0.05058002 -0.14875603
  -0.92964602  1.8945322  -0.00726682 -1.51997244]
 [-0.05058002 -0.22698998 -0.8298521   1.71803808 -0.05058002 -0.14875603
  -0.93118     1.8945322  -0.00726682 -1.51978028]
 [-0.05058002 -0.22698998 -0.8298521   1.7165041  -0.05058002 -0.14875603
  -0.93118     1.8945322  -0.00688345 -1.52169764]
 [-0.05058002 -0.22852397 -0.8298521   1.7165041  -0.05058002 -0.14875603
  -0.93118     1.89606619 -0.0089925  -1.51345265]


In [65]:
# shuffule data
permutation = np.random.permutation(len(all_data))
n_training_data = int(len(all_data) * 0.7)
training_data = permutation[:n_training_data]

## 3. Learn on training data

In scikit-learn, an estimator for classification is a Python object that implements the methods fit(X, y) and predict(T). An example of an estimator is the class sklearn.svm.SVC that implements support vector classification.

In [66]:
clf = svm.SVC(gamma=0.001, C=100.)

### learning

In [166]:
# YOUR CODE HERE
clf.fit(all_data[:-4], all_target[:-4])

SVC(C=100.0, gamma=0.001)

### predicting

In [ ]:
clf.predict(all_data[-1]), all_target[-1]

(array([10]), 10)

In [97]:
def evaluate(expected, predicted):
    print("Classification report:\n%s\n" % metrics.classification_report(expected, predicted))

    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

In [167]:
expected = []
predicted = []
# YOUR CODE HERE
expected = all_target[-100:]
predicted = clf.predict(all_data[-100:])

evaluate(expected, predicted)

Classification report:
              precision    recall  f1-score   support

           2       0.00      0.00      0.00         0
           7       1.00      0.91      0.95        11
           8       1.00      1.00      1.00        26
           9       1.00      1.00      1.00        11
          10       1.00      1.00      1.00        52

    accuracy                           0.99       100
   macro avg       0.80      0.78      0.79       100
weighted avg       1.00      0.99      0.99       100


Confusion matrix:
[[ 0  0  0  0  0]
 [ 1 10  0  0  0]
 [ 0  0 26  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 52]]


c:\Users\willy\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\willy\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\willy\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita

## 4. Evaluate on the test data

In [168]:
expected = []
predicted = []
# YOUR CODE HERE
expected = all_target[-204:]
predicted = clf.predict(all_data[-204:])

evaluate(expected, predicted)

Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.91      0.95        11
           2       0.97      1.00      0.98        30
           3       1.00      1.00      1.00        10
           4       1.00      1.00      1.00        10
           5       1.00      1.00      1.00        10
           6       1.00      1.00      1.00        20
           7       1.00      0.91      0.95        11
           8       1.00      1.00      1.00        26
           9       0.92      1.00      0.96        11
          10       1.00      1.00      1.00        52

    accuracy                           0.99       204
   macro avg       0.99      0.98      0.99       204
weighted avg       0.99      0.99      0.99       204


Confusion matrix:
[[13  0  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  1  0]
 [ 0  0 30  0  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0  0  0  0]
 

## 5. Deploy to the real system

We can simple use `pickle` module to serialize the trained classifier.

In [ ]:
import pickle
ROBOT_POSE_CLF = 'robot_pose.pkl'
pickle.dump(clf, open(ROBOT_POSE_CLF, 'wb'))

Then, in the application we can load the trained classifier again.

In [ ]:
clf2 = pickle.load(open(ROBOT_POSE_CLF))
clf2.predict(all_data[-1]), all_target[-1]

(array([10]), 10)